# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Example values from UDS package repo template
# host: tinkerbell
domain: "###ZARF_VAR_DOMAIN###"
# Support for custom `network.allow` entries on the Package CR
exemptionEnabled: true
udsEnabled: true
additionalNetworkAllow: []
#    # Notice no `remoteGenerated` field here on custom internal rule
#   - direction: Ingress
#     selector:
#       app: jenkins
#     remoteNamespace: jenkins
#     remoteSelector:
#       app: jenkins
#     port: 8180
#     description: "Ingress from Jenkins"
#   # No `remoteNamespace`, `remoteSelector`, or `port` fields on rule to `remoteGenerated`
#   - direction: Egress
#     selector:
#       app: webservice
#     remoteGenerated: Anywhere
#     description: "Egress from tinkerbell"
